// This file is generated by Slice Machine. Update with care!

import Footer from './Footer';
import HeroText from './HeroText';
import MarqueeText from './MarqueeText';
import MissionText from './MissionText';
import NavBar from './NavBar';
import Partners from './Partners';
import SliceTest from './SliceTest';
import Values from './Values';

export {
  Footer,
  HeroText,
  MarqueeText,
  MissionText,
  NavBar,
  Partners,
  SliceTest,
  Values,
};

export const components = {
  footer: Footer,
  hero_text: HeroText,
  marquee_text: MarqueeText,
  mission_text: MissionText,
  nav_bar: NavBar,
  partners: Partners,
  slice_test: SliceTest,
  values: Values,
};
